# Generated by Django 5.2.11 on 2026-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='number',
            field=models.CharField(default='09101742390', max_length=11),
            preserve_default=False,
        ),
    ]
