# Generated by Django 5.2.11 on 2026-07-06 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل باید با 09 شروع شده و 11 رقم باشد.",
                        regex="^09\\d{9}$",
                    )
                ],
            ),
        ),
    ]
