# Generated by Django 5.2.11 on 2026-04-04 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('QUOTED', 'Quoted'), ('CONFIRMED', 'Confirmed'), ('PRODUCTION', 'In Production'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='NEW', max_length=12)),
                ('fabric_by_workshop', models.BooleanField(default=False)),
                ('materials_by_workshop', models.BooleanField(default=False)),
                ('staff_note', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Item title (e.g. Men's Jacket, Pants, Coat)", max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_currency', models.CharField(default='IRR', max_length=3)),
                ('unit_price_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('fabric_type', models.CharField(blank=True, max_length=100)),
                ('lining_type', models.CharField(blank=True, max_length=100)),
                ('extra_materials', models.TextField(blank=True)),
                ('size_mode', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP')], default='NORMAL', max_length=10)),
                ('size_from', models.CharField(blank=True, max_length=50)),
                ('size_to', models.CharField(blank=True, max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip'])])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Order File',
                'verbose_name_plural': 'Order Files',
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Message',
                'verbose_name_plural': 'Order Messages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', models.CharField(default='IRR', max_length=3)),
                ('amount_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItemVipSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_sizes', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'VIP Size',
                'verbose_name_plural': 'VIP Sizes',
                'unique_together': {('order_item', 'size')},
            },
        ),
    ]
