# Generated by Django 5.2.11 on 2026-04-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_type', 'stage'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('MATERIAL', 'خرید پارچه/متریال'), ('EXECUTION', 'اجرا')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stage',
            field=models.CharField(choices=[('FULL', 'کامل'), ('CUTTING', 'برش'), ('SEWING', 'دوخت'), ('IRONING', 'اتو و بسته\u200cبندی'), ('READY', 'آماده تحویل')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'پرداخت شده'), ('INACTIVE', 'غیر فعال'), ('PAYABLE', 'قابل پرداخت')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('MATERIAL', 'خرید پارچه/متریال'), ('EXECUTION', 'اجرا')], max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Tax rate in percentage (default 10%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='پیش\u200cفاکتور مرتبط با این پرداخت', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.invoice'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='عدد', help_text='Unit of measurement (e.g. متر, عدد, کیلو)', max_length=50)),
                ('unit_price_currency', models.CharField(default='IRR', max_length=3)),
                ('unit_price_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
