# Generated by Django 5.2.11 on 2026-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_options_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['service_type', 'stage_order'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_type',
            new_name='service_type',
        ),
        migrations.AddField(
            model_name='order',
            name='fabric_cost_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='هزینه خرید پارچه توسط کارگاه', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='fabric_cost_currency',
            field=models.CharField(default='IRR', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='materials_cost_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='هزینه خرج کار/متریال توسط کارگاه', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='materials_cost_currency',
            field=models.CharField(default='IRR', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مجموع قیمت آیتم\u200cها (محاسبه شده)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_currency',
            field=models.CharField(default='IRR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='stage_order',
            field=models.IntegerField(default=0, help_text='ترتیب مرحله برای مرتب\u200cسازی'),
        ),
    ]
