# Generated by Django 5.2.11 on 2026-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_options_remove_payment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'جدید'), ('REVIEW', 'درحال بررسی'), ('QUOTED', 'در انتظار پرداخت'), ('CONFIRMED', 'تایید شده'), ('PRODUCTION', 'درحال تولید'), ('READY', 'آماده تحویل'), ('DELIVERED', 'تحویل شده'), ('CANCELED', 'لغو شده')], default='NEW', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stage',
            field=models.CharField(choices=[('FULL', 'خرج کار و پارچه'), ('CUTTING', 'برش'), ('SEWING', 'دوخت'), ('IRONING', 'اتو و بسته\u200cبندی'), ('READY', 'آماده تحویل')], default='FULL', max_length=20),
        ),
    ]
