# Generated by Django 5.2.11 on 2026-04-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_gateway_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric_cost_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric_cost_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='materials_cost_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='materials_cost_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount_currency',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra_materials',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='lining_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_currency',
        ),
    ]
