# Generated by Django 5.2.11 on 2026-04-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_customer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=0, default=10, help_text='Tax rate in percentage (default 10%)', max_digits=5),
        ),
    ]
