# Generated by Django 5.2.11 on 2026-04-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_invoice_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
