# Generated by Django 5.2.11 on 2026-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, help_text='زرین پال authority code for this payment', max_length=64, null=True),
        ),
    ]
