# Generated by Django 5.2.11 on 2026-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_mode',
            field=models.CharField(choices=[('NORMAL', 'عادی'), ('VIP', 'VIP')], default='NORMAL', max_length=10),
        ),
    ]
