# Generated by Django 5.2.11 on 2026-06-19 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_order_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="order",
            name="stage_num",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
