# Generated by Django 5.2.11 on 2026-07-06 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_order_stage_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stage_num",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
